version: "1.0"
info:
  model: int-scaffold
packages:
- name: KusiazstagetestProject
  gitServerName: kusiAzStage2
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SIQAJDBCAdapterTests
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
services:
- serviceName: project.kusiazstagetest.integrations:Sum
  packages:
  - name: KusiazstagetestProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.kusiazstagetest.integrations:deepclonetest
  packages:
  - name: KusiazstagetestProject
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.kusiazstagetest.integrations:salesforceTest
  packages:
  - name: KusiazstagetestProject
    version: "1.0"
- serviceName: project.siqatest1009.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.operations.actions:SalesAccount
  packages:
  - name: KusiazstagetestProject
    version: "1.0"
